
name : Cowsay Workflow
on : 
    push: 
     branches:
          - main
     paths:
            - '.github/workflows/cowsay.yaml'
jobs :
  cowsay_draw :
    runs-on : ubuntu-latest
    steps :
      - name : Checkout Repository
        uses : actions/checkout@v2

jobs:
    cowsay-draw:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Install Cowsay
              run: sudo apt-get install -y cowsay

            - name: Run COwsay cmd
              run: cowsay -f dragon "This is a dragon saying hello!" >> dragon.txt

            - name: check file
              run: grep -i "dragon" dragon.txt

            - name: Read file
              run: cat dragon.txt